---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            python: 2.7
            architecture: x86
          - os: windows-2022
            python: 2.7
            architecture: x86
        os:
          - macos-12
          - macos-13
          - macos-14
          - windows-2019
          - windows-2022
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
        python: ["2.7", "3.11"]
        architecture: ["x64"]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        id: python
        uses: ./
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade -r requirements-dev.txt

      - name: Test with pytest
        id: test
        env:
          INPUT_PYTHON_VERSION: ${{ matrix.python }}
        shell: bash
        run: |
          python -m pytest \
            -rxXs \
            --tb=native \
            --verbose \
            tests

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup-release
        uses: LizardByte/setup-release-action@v2024.520.193857
        with:
          fail_on_events_api_error: true
          github_token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Create Release
        id: action
        uses: LizardByte/create-release-action@v2024.520.193838
        with:
          allowUpdates: false
          artifacts: ''
          discussionCategory: announcements
          generateReleaseNotes: true
          name: ${{ steps.setup-release.outputs.release_tag }}
          prerelease: true
          tag: ${{ steps.setup-release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
